### ISSUE TITLE
topera/plugins/pricillapluginmanager.py SyntaxError

### ISSUE THREAD

**Issue by fgeek** [toperaproject/topera#1]
```
henri@test:~/scm/topera$ python topera.py 
Traceback (most recent call last):
  File "topera.py", line 67, in <module>
    from topera.plugins.pricillapluginmanager import *
  File "/home/fgeek/scm/topera/topera/plugins/pricillapluginmanager.py", line 358
    return { plugin: self.__plugins[plugin] for plugin in self.__plugins if plugin.startswith(category) }
                                          ^
SyntaxError: invalid syntax
```

**Comment by cr0hn** [comment]
We tested Topera under OSX, Ubuntu and Backtrack 5 and it runs well.

What system and python version are you using?

**Comment by fgeek** [comment]
Python 2.5.5 in Debian squeeze 2.5.5-11 NOT OK.
Python 2.6.6 in Debian squeeze 2.6.6-8+b1 NOT OK.
Python 2.7.3 in Debian sid 2.7.3-6 OK.
Python 2.6.8 in Debian sid 2.6.8-1.1 says "[!] You must use python 2.7 or greater".
Python 2.7.3 in Debian squeeze from sources OK.

**Comment by cr0hn** [comment]
With python 2.7 it runs?

**Comment by fgeek** [comment]
Yes. "[!] You must use python 2.7 or greater" -check might be in the wrong place. It should be done before that import.

**Comment by cr0hn** [comment]
Oks. Topera uses argparse library that are not included in 2.6.5. When it tries to import it, display that exception. We are not tested in others versions of python and not provide support for them, sorry.

**Comment by fgeek** [comment]
```
diff --git a/topera.py b/topera.py
index 7eab4f2..21cb319 100755
--- a/topera.py
+++ b/topera.py
@@ -37,6 +37,11 @@ __status__ = "Testing"
 import sys
 import os.path as path

+# Check that user is running at least Python 2.7 version.
+if sys.version_info < (2, 7):
+    print "\n[!] You must use Python 2.7 or greater\n"
+    sys.exit(1)
+
 try:
        import argparse
 except ImportError:
@@ -117,11 +122,6 @@ if __name__ == '__main__':

        Credits()

-       # Check for python version
-       if sys.version_info < (2, 7):
-               print "\n[!] you must use python 2.7 or greater\n"
-               sys.exit(1)
-
        # Check if running user is root
        if not get_user():
                print "\n[!] You must be root to run %s\n" % (__prog__)
```

Not supporting older versions is ok. Add information about it to "How to use it?" -section in front page or something similar. For example new requirements-section.

**Comment by cr0hn** [comment]
Ummm... Oks, now I understand you :) Thanks Henri. It's now fixed in the repository.
