### ISSUE TITLE
Distribution request

### ISSUE THREAD

**Issue by archey** [toperaproject/topera#2]
I am a developer for archassault(https://github.com/ArchAssault-Project), we would like to distribute this in our distro. Can you please add a license file as well as give us permission to distribute the file in our distro?

**Comment by toperaproject** [comment]
Hello arch3y!

```
Sound good! Of course you can add Topera in your distro :)

What do you need?
```

Cheers!

**Comment by archey** [comment]
I just need to know which opensource license you are going to use: GPL, MIT, APACHE, BSD, GPL2, GPL3, or are you using your own license. We just need make sure we have the proper license in our pkg so that we can distribute it properly.  You can add a license file from GH, for example our project is GPL3. I would read over the licenses and pick one that best suites you and let us know which one you decide on.

**Comment by cr0hn** [comment]
Topera is GPL2. I just added LICENSE file into the repository.

**Comment by archey** [comment]
Thanks we will update our pkgbuild approrpriately
